
classes::include:
  - "profile::desktop"

desktop::packages::install:
  - "vim-enhanced"
  - "git"
  - "curl"
  - "google-chrome-stable"
  - "VirtualBox-5.0"
  - "dkms"
  - "kernel-devel"
  - "gcc"
  - "vagrant"
  - "docker"
  - "owncloud-client"
  - "skype"
  - "gimp"
  - "thunderbird"
  - "chrome-gnome-shell"
  - "gnome-tweak-tool.noarch"
