
- name: docker
  src: https://github.com/geerlingguy/ansible-role-docker.git
  version: master

- name: atom
  src: https://github.com/jdauphant/ansible-role-atom.git
  version: master

- name: chrome
  src: https://github.com/cmprescott/ansible-role-chrome.git
  version: master
